@startuml 出欠席管理システム
left to right direction
actor 教師
actor 管理者
rectangle 出席管理システム {
usecase 教師アカウントを登録する
usecase 教師アカウントを編集する
usecase 教師アカウントを削除する
usecase ログインする
usecase ログアウトする
usecase 学生情報を登録する
usecase 学生情報を編集する
usecase 学生情報を削除する
usecase 学生を検索する
usecase 教科を登録する
usecase 教科を編集する
usecase 教科を削除する
usecase 時間割を登録する
usecase 時間割を編集する
usecase 時間割を削除する
usecase 出欠席を登録する
usecase 出欠席を編集する
usecase 出席状況を表示する
}
管理者 --|> 教師
教師 --> ログアウトする
教師 --> ログインする
管理者 --> 教師アカウントを登録する
管理者 --> 教師アカウントを編集する
管理者 --> 教師アカウントを削除する
教師 --> 学生情報を登録する
教師 --> 学生情報を編集する
教師 --> 学生情報を削除する
教師 --> 学生を検索する
教師 --> 教科を登録する
教師 --> 教科を編集する
教師 --> 教科を削除する
教師 --> 時間割を登録する
教師 --> 時間割を編集する
教師 --> 時間割を削除する
教師 ----> 出欠席を登録する
教師 ---> 出欠席を編集する
教師 -----> 出席状況を表示する
@enduml